### ISSUE TITLE
写的代码像诗一样优雅？

### ISSUE THREAD

**Issue by Cai-zj** [seaung/MBook#1]
求大佬整理一份Java学习手册

**Comment by seaung** [comment]
> 求大佬整理一份Java学习手册

您好,暂时对java还没什么想法,就不整理了.后续做java代码审计是会做一些相关的笔记的

**Comment by Cai-zj** [comment]
为了你的发际线考虑，暂时不碰Java ？
不 不 不，只有光头才能变强

**Comment by seaung** [comment]
啊这。。。变强不一定要秃头的哟

**Comment by Cai-zj** [comment]
看过一拳超人吗？？？

**Comment by seaung** [comment]
看过，但是我不是琦玉老师

**Comment by Cai-zj** [comment]
你是李老师，(⊙o⊙)…   李老师？ 有点耳熟

**Comment by seaung** [comment]
啊这。。。叫老师还不至于
